extends: airbnb-base
rules: # see https://eslint.org/docs/rules/
  indent: [error, 4]
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  no-console: off
  camelcase: off
  strict: off
